POST http://localhost:3000/api/products
Content-Type: application/json

{
            "_id": 4,
            "name": "Mi Band 9",
            "rating": 3,
            "sales": 28,
            "category": "smartwatches",
            "brand": "Xiaomi",
            "seller": "Xiaomi Global",
            "price": 328.64,
            "offer": "27",
            "latest": true,
            "bestseller": false,
            "featured": true,
            "description": "Momentos extraordinários com a lente Leica e sensor Sony IMX906. Desfrute de fotos nítidas mesmo em baixa luz e explore sua criatividade com estilos fotográficos exclusivos Leica. Tela Imersiva com IA, excepcional em qualquer ambiente. Mergulhe em conteúdos vibrantes com o display CrystalRes IA de 144Hz. Com brilho de até 4000 nits e ajustes automáticos inteligentes. Criatividade Impulsionada por IA. Libere seu potencial criativo com ferramentas de IA avançadas. Edite fotos, crie vídeos e experimente recursos inovadores como o Intérprete de IA e o Circule para Pesquisar do Google. Desempenho Poderoso, Eficiente e Resistente. Processador de alta velocidade Dimensity 9300 Plus MediaTek, tecnologia HyperCharge com carregador de 67W, recarrega 100% da bateria em até 45 minutos e certificação IP68 contra água e poeira. Tudo isso com acesso à livros digitais que somente a Xiaomi oferece."
            ,
            "variations": [
                {
                    "variation": "Preto",
                    "order": 1
                }
            ],
            "comments": [
                {
                    "_id": 1,
                    "rating": 5,
                    "variation": "Preto",
                    "customer": "Liam Smith",
                    "customerimage": "",
                    "date": "01 Jul. 2025",
                    "text": "The Mi Band 9 is fantastic! It has a sleek design and tracks my workouts perfectly.",
                    "images": [
                        {
                            "src": "https://example.com/mi_band_9_image.jpg",
                            "order": 1
                        }
                    ]
                },
                {
                    "_id": 2,
                    "rating": 4,
                    "variation": "Preto",
                    "customer": "Emma Johnson",
                    "date": "01 Jul. 2025",
                    "text": "Great value for money! The battery lasts long, but I wish it had NFC."
                },
                {
                    "_id": 3,
                    "rating": 3,
                    "variation": "Preto",
                    "customer": "Noah Brown",
                    "date": "01 Jul. 2025",
                    "text": "It's decent, but the accuracy could be better compared to other brands."
                },
                {
                    "_id": 4,
                    "rating": 2,
                    "variation": "Preto",
                    "customer": "Olivia Davis",
                    "date": "01 Jul. 2025",
                    "text": "Not very satisfied. The interface is a bit confusing and lacks some features."
                },
                {
                    "_id": 5,
                    "rating": 1,
                    "variation": "Preto",
                    "customer": "James Wilson",
                    "date": "01 Jul. 2025",
                    "text": "Very disappointed. The watch stopped syncing after a week."
                },
                {
                    "_id": 6,
                    "rating": 1,
                    "variation": "Preto",
                    "customer": "Sophia Martinez",
                    "date": "01 Jul. 2025",
                    "text": "Terrible experience. Would not recommend."
                }
            ],
            "images": [
                {
                    "src": "https://renan-nxscimento.github.io/Merchant_E-commerce/img/watches/mband9.png",
                    "order": 1
                },
                {
                    "src": "https://renan-nxscimento.github.io/Merchant_E-commerce/img/watches/AltImgs/miband9/alt1.webp",
                    "order": 2
                },
                {
                    "src": "https://renan-nxscimento.github.io/Merchant_E-commerce/img/watches/AltImgs/miband9/alt2.webp",
                    "order": 3
                },
                {
                    "src": "https://renan-nxscimento.github.io/Merchant_E-commerce/img/watches/AltImgs/miband9/alt3.webp",
                    "order": 4
                }
            ],
            "details": [
                {
                    "detail": "Capacidade da bateria",
                    "order": 1,
                    "spec": "233mAh"
                },
                {
                    "detail": "Possui câmera",
                    "order": 2,
                    "spec": "Não"
                },
                {
                    "detail": "Material da pulseira",
                    "order": 3,
                    "spec": "Silicone"
                },
                {
                    "detail": "Tela",
                    "order": 4,
                    "spec": "1,62 Polegadas"
                },
                {
                    "detail": "Duração da bateria",
                    "order": 5,
                    "spec": "Até 21 Dias"
                },
                {
                    "detail": "Extras",
                    "order": 6,
                    "spec": "Proteção IP68 contra águe e poeira"
                }
            ]
        }

###
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "theboss",
    "nickname": "The Boss",
    "email": "thisemail@tester.com",
    "password": "thebosseater",
    "image": "https://thenewheroines.wordpress.com/wp-content/uploads/2017/05/30fda328355410e7839666921384aac2.png",
    "favorite_products": [

    ],
    "cart": [

    ]
}

###
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "test bot",
    "nickname": "Punished ''Venom'' tester",
    "email": "tester@tester.com",
    "password": "bigtest",
    "image": "https://64.media.tumblr.com/0e741f51d477680bca91c71931139fb8/9a2b25f80bcb6ded-32/s500x750/11f5fb1471fd058c485b4b5b7907826c5a9b23a8.png",
    "favorite_products": [

    ],
    "cart": [

    ]
}

###
PUT http://localhost:3000/api/users/683fbfe59d6021080a9a7212
Content-Type: application/json

{
    "name": "Diamond Dog",
    "nickname": "Punished ''Venom'' Jotchua",
    "email": "tester@tester.com",
    "password": "bigtest",
    "image": "https://64.media.tumblr.com/0e741f51d477680bca91c71931139fb8/9a2b25f80bcb6ded-32/s500x750/11f5fb1471fd058c485b4b5b7907826c5a9b23a8.png",
    "favorite_products": [
        {
            "productname": "Rog Phone 8" 
        }
    ],
    "cart": [
        {
            "productname": "Rog Phone 8",
            "quantity": 3,
            "variation": "256GB 8GB"
        }
    ]
}

###
DELETE http://localhost:3000/api/users/683fbf569d6021080a9a71cc