POST http://localhost:3000/api/products
Content-Type: application/json

{
            "_id": 3,
            "name": "Mi 14t Pro",
            "rating": 3,
            "reviews": 6,
            "sales": 28,
            "category": "smartphones",
            "brand": "Xiaomi",
            "seller": "The man who sold the World",
            "price": 4999.12,
            "offer": "",
            "latest": true,
            "bestseller": false,
            "featured": true,
            "description": "Momentos extraordinários com a lente Leica e sensor Sony IMX906. Desfrute de fotos nítidas mesmo em baixa luz e explore sua criatividade com estilos fotográficos exclusivos Leica. Tela Imersiva com IA, excepcional em qualquer ambiente. Mergulhe em conteúdos vibrantes com o display CrystalRes IA de 144Hz. Com brilho de até 4000 nits e ajustes automáticos inteligentes. Criatividade Impulsionada por IA. Libere seu potencial criativo com ferramentas de IA avançadas. Edite fotos, crie vídeos e experimente recursos inovadores como o Intérprete de IA e o Circule para Pesquisar do Google. Desempenho Poderoso, Eficiente e Resistente. Processador de alta velocidade Dimensity 9300 Plus MediaTek, tecnologia HyperCharge com carregador de 67W, recarrega 100% da bateria em até 45 minutos e certificação IP68 contra água e poeira. Tudo isso com acesso à livros digitais que somente a Xiaomi oferece."
            ,
            "variations": [
                {
                    "variation": "256GB 12GB",
                    "order": 1
                },
                {
                    "variation": "512GB 12GB",
                    "order": 2
                },
                {
                    "variation": "1TB 12GB",
                    "order": 3
                }
            ],
            "comments": [
                {
                    "_id": 1,
                    "rating": 5,
                    "variation": "256GB 12GB",
                    "customer": "Big Boss",
                    "date": "11 Jul. 2007",
                    "text": "Foto do ROG 5. Em relação ao ROG 5, este ROG 8 possui qualidade de alto falante inferior, qualidade de camera superior, mas o que me surpreende é a diferença de peso O ROG 8 é absurdamente mais leve que o ROG 5. Demoraram 7 dias para postar o produto mas assim que postaram chegou no dia seguinte",
                    "images": [
                        {
                            "src": "https://static.wikia.nocookie.net/metalgear/images/6/64/Img_mgsv_idroid.jpg/revision/latest/scale-to-width-down/474?cb=20230106043946&path-prefix=pt"
                        }
                    ]
                },
                {
                    "_id": 2,
                    "rating": 5,
                    "variation": "256GB 12GB",
                    "customer": "Big Boss",
                    "date": "11 Jul. 2007"
                },
                {
                    "_id": 3,
                    "rating": 4,
                    "variation": "256GB 12GB",
                    "customer": "Big Boss",
                    "date": "11 Jul. 2007"
                },
                {
                    "_id": 4,
                    "rating": 2,
                    "variation": "256GB 12GB",
                    "customer": "Big Boss",
                    "date": "11 Jul. 2007"
                },
                {
                    "_id": 5,
                    "rating": 1,
                    "variation": "256GB 12GB",
                    "customer": "Big Boss",
                    "date": "11 Jul. 2007"
                },
                {
                    "_id": 6,
                    "rating": 1,
                    "variation": "256GB 12GB",
                    "customer": "Big Boss",
                    "date": "11 Jul. 2007"
                }
            ],
            "images": [
                {
                    "src": "https://pbs.twimg.com/media/BkqjX6ICIAAU_iB.jpg",
                    "order": 1
                },
                {
                    "src": "https://assetsio.gnwcdn.com/mgs-v-sells-6m-pushes-konami-digital-profits-up-by-250-percent-1454068524241.jpg?width=1600&height=900&fit=crop&quality=100&format=png&enable=upscale&auto=webp",
                    "order": 2
                },
                {
                    "src": "https://meups.com.br/wp-content/uploads/2022/10/Metal-gear-Solid-MGS.jpg",
                    "order": 3
                },
                {
                    "src": "https://planetagracza.pl/wp-content/uploads/2015/08/MGS-V-The-Phantom-Pain.jpg",
                    "order": 4
                },
                {
                    "src": "https://gamehall.com.br/wp-content/uploads/2015/08/Metal-Gear-Solid-V-The-Phantom-Pain-Control-room-PS4.jpg",
                    "order": 5
                }
            ],
            "details": [
                {
                    "detail": "Capacidade",
                    "order": 1,
                    "spec": 256
                },
                {
                    "detail": "Memória RAM",
                    "order": 2,
                    "spec": "12GB/16GB"
                },
                {
                    "detail": "Câmera",
                    "order": 3,
                    "spec": "50MP"
                },
                {
                    "detail": "Câmera frontal",
                    "order": 4,
                    "spec": "12MP"
                },
                {
                    "detail": "Processador",
                    "order": 5,
                    "spec": "Snapdragon 8 Gen 3"
                },
                {
                    "detail": "Tela",
                    "order": 6,
                    "spec": "6,78' 165hz"
                },
                {
                    "detail": "Sistema operacional",
                    "order": 7,
                    "spec": "Android"
                },
                {
                    "detail": "Extras",
                    "order": 8,
                    "spec": "NFC, Proteção IP68, entrada de 3.5mm"
                }
            ]
        }

###
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "theboss",
    "email": "testeremail@tester.com",
    "password": "thebosseater",
    "image": "",
    "favorite_products": [

    ],
    "cart": [

    ]
}

###
PUT http://localhost:3000/api/users/683084c9d876c15111ea2356
Content-Type: application/json

{
    "name": "tester",
    "email": "testeremail@tester.com",
    "password": "snakeeater",
    "image": "",
    "favorite_products": [
        {
            "productname": "Rog Phone 8" 
        }
    ],
    "cart": [
        {
            "productname": "Rog Phone 8",
            "quantity": 3,
            "variation": "256GB 8GB"
        }
    ]
}