POST http://localhost:3000/api/products
Content-Type: application/json

{
            "_id": 4,
            "name": "Mi Band 9",
            "rating": 3,
            "sales": 28,
            "category": "smartwatches",
            "brand": "Xiaomi",
            "seller": "Xiaomi Global",
            "price": 4999.12,
            "offer": "",
            "latest": true,
            "bestseller": false,
            "featured": true,
            "description": "Momentos extraordinários com a lente Leica e sensor Sony IMX906. Desfrute de fotos nítidas mesmo em baixa luz e explore sua criatividade com estilos fotográficos exclusivos Leica. Tela Imersiva com IA, excepcional em qualquer ambiente. Mergulhe em conteúdos vibrantes com o display CrystalRes IA de 144Hz. Com brilho de até 4000 nits e ajustes automáticos inteligentes. Criatividade Impulsionada por IA. Libere seu potencial criativo com ferramentas de IA avançadas. Edite fotos, crie vídeos e experimente recursos inovadores como o Intérprete de IA e o Circule para Pesquisar do Google. Desempenho Poderoso, Eficiente e Resistente. Processador de alta velocidade Dimensity 9300 Plus MediaTek, tecnologia HyperCharge com carregador de 67W, recarrega 100% da bateria em até 45 minutos e certificação IP68 contra água e poeira. Tudo isso com acesso à livros digitais que somente a Xiaomi oferece."
            ,
            "variations": [
                {
                    "variation": "Preto",
                    "order": 1
                }
            ],
            "comments": [
                {
                    "_id": 1,
                    "rating": 5,
                    "variation": "Preto",
                    "customer": "Big Boss",
                    "date": "11 Jul. 2007",
                },
                {
                    "_id": 2,
                    "rating": 5,
                    "variation": "Preto",
                    "customer": "Big Boss",
                    "date": "11 Jul. 2007"
                },
                {
                    "_id": 3,
                    "rating": 4,
                    "variation": "Preto",
                    "customer": "Big Boss",
                    "date": "11 Jul. 2007"
                },
                {
                    "_id": 4,
                    "rating": 2,
                    "variation": "Preto",
                    "customer": "Big Boss",
                    "date": "11 Jul. 2007"
                },
                {
                    "_id": 5,
                    "rating": 1,
                    "variation": "Preto",
                    "customer": "Big Boss",
                    "date": "11 Jul. 2007"
                },
                {
                    "_id": 6,
                    "rating": 1,
                    "variation": "Preto",
                    "customer": "Big Boss",
                    "date": "11 Jul. 2007"
                }
            ],
            "images": [
                {
                    "src": "https://pbs.twimg.com/media/BkqjX6ICIAAU_iB.jpg",
                    "order": 1
                },
                {
                    "src": "https://assetsio.gnwcdn.com/mgs-v-sells-6m-pushes-konami-digital-profits-up-by-250-percent-1454068524241.jpg?width=1600&height=900&fit=crop&quality=100&format=png&enable=upscale&auto=webp",
                    "order": 2
                },
                {
                    "src": "https://meups.com.br/wp-content/uploads/2022/10/Metal-gear-Solid-MGS.jpg",
                    "order": 3
                },
                {
                    "src": "https://planetagracza.pl/wp-content/uploads/2015/08/MGS-V-The-Phantom-Pain.jpg",
                    "order": 4
                },
                {
                    "src": "https://gamehall.com.br/wp-content/uploads/2015/08/Metal-Gear-Solid-V-The-Phantom-Pain-Control-room-PS4.jpg",
                    "order": 5
                }
            ],
            "details": [
                {
                    "detail": "Capacidade",
                    "order": 1,
                    "spec": 256
                },
                {
                    "detail": "Memória RAM",
                    "order": 2,
                    "spec": "12GB/16GB"
                },
                {
                    "detail": "Câmera",
                    "order": 3,
                    "spec": "50MP"
                },
                {
                    "detail": "Câmera frontal",
                    "order": 4,
                    "spec": "12MP"
                },
                {
                    "detail": "Processador",
                    "order": 5,
                    "spec": "Snapdragon 8 Gen 3"
                },
                {
                    "detail": "Tela",
                    "order": 6,
                    "spec": "6,78' 165hz"
                },
                {
                    "detail": "Sistema operacional",
                    "order": 7,
                    "spec": "Android"
                },
                {
                    "detail": "Extras",
                    "order": 8,
                    "spec": "NFC, Proteção IP68, entrada de 3.5mm"
                }
            ]
        }

###
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "theboss",
    "nickname": "The Boss",
    "email": "thisemail@tester.com",
    "password": "thebosseater",
    "image": "https://thenewheroines.wordpress.com/wp-content/uploads/2017/05/30fda328355410e7839666921384aac2.png",
    "favorite_products": [

    ],
    "cart": [

    ]
}

###
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "test bot",
    "nickname": "Punished ''Venom'' tester",
    "email": "tester@tester.com",
    "password": "bigtest",
    "image": "https://64.media.tumblr.com/0e741f51d477680bca91c71931139fb8/9a2b25f80bcb6ded-32/s500x750/11f5fb1471fd058c485b4b5b7907826c5a9b23a8.png",
    "favorite_products": [

    ],
    "cart": [

    ]
}

###
PUT http://localhost:3000/api/users/683fbfe59d6021080a9a7212
Content-Type: application/json

{
    "name": "Diamond Dog",
    "nickname": "Punished ''Venom'' Jotchua",
    "email": "tester@tester.com",
    "password": "bigtest",
    "image": "https://64.media.tumblr.com/0e741f51d477680bca91c71931139fb8/9a2b25f80bcb6ded-32/s500x750/11f5fb1471fd058c485b4b5b7907826c5a9b23a8.png",
    "favorite_products": [
        {
            "productname": "Rog Phone 8" 
        }
    ],
    "cart": [
        {
            "productname": "Rog Phone 8",
            "quantity": 3,
            "variation": "256GB 8GB"
        }
    ]
}

###
DELETE http://localhost:3000/api/users/683fbf569d6021080a9a71cc